### ISSUE TITLE
Pasting multiline values gets smushed into one line

### ISSUE THREAD

**Issue by jared-hughes** [Heavenira/wolfram2desmos#17]
For example, copy-paste

```
y=x
y=2
y=4
```
into Desmos. It inserts as one line instead of several as expected.

![image](https://user-images.githubusercontent.com/20214911/118100409-44bd1300-b38b-11eb-81c0-d04596d2e18f.png)

Might be able to fix this by first splitting the input on newlines, then transforming each line individually.

**Comment by Heavenira** [comment]
Acknowledged. I will look into this, and will check if `\n` can be read from the clipboard.
