### ISSUE TITLE
Regex checking shouldn't use `|`

### ISSUE THREAD

**Issue by donno2048** [Heavenira/wolfram2desmos#21]
Use `/[A-Za-z]/` not `/[A-Z|a-z]/`, for example:
https://github.com/Heavenira/wolfram2desmos/blob/a312b1f3fb27165ee14a01b491bf43372a89afea/wolfram2desmos.user.js#L120

**Comment by donno2048** [comment]
I can create a PR to fix it

**Comment by Heavenira** [comment]
Whoops!! Good catch @donno2048! I can't believe I let that one slip by. You can probably see that my RegEx was a bit rubbish when I made this :D
Feel free to fix it in `wolfram2desmos.user.js`. I will make the changes to `wolfram2desmos v2.js` instead, which is what I use in [DesModder](https://github.com/DesModder/DesModder).
